language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - bin/kahlan --clover=clover.xml

after_success:
  - "if [ $(phpenv version-name) = '7.0' ]; then curl -F 'json_file=@coveralls.json' https://coveralls.io/api/v1/jobs --verbose; fi"
  - "if [ $(phpenv version-name) = '7.0' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - "if [ $(phpenv version-name) = '7.0' ]; then php ocular.phar code-coverage:upload --format=php-clover 'clover.xml'; fi"