language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true
  
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - composer dump-autoload -o
  - if [[ $TRAVIS_PHP_VERSION =~ ^7 ]]; then git clone git://github.com/xdebug/xdebug.git && cd xdebug && phpize && ./configure --enable-xdebug  && make && make install; fi

script:
  - bin/kahlan --coverage=4 --reporter=verbose
  
notifications:
    email: false